name: 🧩 CI · Merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: podlord-merge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_dotnet_build_common.yml@a6f230e7a31ec0f44951200e29dab1639f7309c5
    with:
      ref: ${{ github.sha }}
      dry_run: true
  native:
    needs: build
    uses: YunaBraska/YunaBraska/.github/workflows/wc_dotnet_build_native.yml@a6f230e7a31ec0f44951200e29dab1639f7309c5
    with:
      version: ${{ needs.build.outputs.version }}
