# yuna-release: true
name: 🏷️ CD · Release

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force.
        required: true
        default: false
        type: boolean

permissions:
  actions: read
  contents: write

jobs:
  release:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_dotnet_release.yml@a6f230e7a31ec0f44951200e29dab1639f7309c5
    with:
      force: ${{ inputs.force }}
