# yuna-release: true
name: 🏷️ CD · Release

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force.
        required: true
        default: false
        type: boolean

permissions:
  actions: read
  contents: write

jobs:
  release:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_dotnet_release.yml@726750fe689eaec2d338410c83fe91a7b3ff4b11
    with:
      force: ${{ inputs.force }}
